[metadata]
maintainers = ["zhanglei.sec@bytedance.com"]

[config]
version = "1.6.0.0"
ko_url = [
"https://lf3-elkeid.bytetos.com/elkeid-download/ko/",
"https://lf6-elkeid.bytetos.com/elkeid-download/ko/",
"https://lf9-elkeid.bytetos.com/elkeid-download/ko/",
"https://lf26-elkeid.bytetos.com/elkeid-download/ko/"]
pipe_path = "/proc/hids_driver/1"
name = "hids_driver"
socket_path = "../plugin.sock"

[structures.execve]
# common_fields contains [uid,data_type,exe,pid,ppid,pgid,tgid,sid,comm,nodename,sessionid] from kernel,[username,timestamp,exe_hash,ppid_argv,pgid_argv,argv,pid_tree] from user.
common_fields = true
data_type = 59
# additional_fields can overwrite the common fields.Key is fields name,value is one of [kernel,placeholder,user].

[structures.execve.additional_fields]
socket_argv = { index = 0, type = "placeholder" }
argv = { index = 1, type = "kernel" }
run_path = { index = 2, type = "kernel" }
pgid_argv = { index = 3, type = "placeholder" }
stdin = { index = 4, type = "kernel" }
stdout = { index = 5, type = "kernel" }
dip = { index = 6, type = "kernel" }
dport = { index = 7, type = "kernel" }
sip = { index = 8, type = "kernel" }
sport = { index = 9, type = "kernel" }
sa_family = { index = 10, type = "kernel" }
pid_tree = { index = 11, type = "kernel" }
tty = { index = 12, type = "kernel" }
socket_pid = { index = 13, type = "kernel" }
ssh = { index = 14, type = "kernel" }
ld_preload = { index = 15, type = "kernel" }
res = { index = 16, type = "kernel" }

[structures.connect]
common_fields = true
data_type = 42

[structures.connect.additional_fields]
connect_type = { index = 0, type = "kernel" }
sa_family = { index = 1, type = "kernel" }
dip = { index = 2, type = "kernel" }
dport = { index = 3, type = "kernel" }
sip = { index = 4, type = "kernel" }
sport = { index = 5, type = "kernel" }
res = { index = 6, type = "kernel" }

[structures.ptrace]
common_fields = true
data_type = 101

[structures.ptrace.additional_fields]
ptrace_request = { index = 0, type = "kernel" }
target_pid = { index = 1, type = "kernel" }
addr = { index = 2, type = "kernel" }
data = { index = 3, type = "kernel" }
pid_tree = { index = 4, type = "kernel" }

[structures.bind]
common_fields = true
data_type = 49

[structures.bind.additional_fields]
sa_family = { index = 0, type = "kernel" }
sip = { index = 1, type = "kernel" }
sport = { index = 2, type = "kernel" }
res = { index = 3, type = "kernel" }

[structures.update_cred]
common_fields = true
data_type = 604

[structures.update_cred.additional_fields]
pid_tree = { index = 0, type = "kernel" }
old_uid = { index = 1, type = "kernel" }
res = { index = 2, type = "kernel" }
old_username = { index = 3, type = "user" }

[structures.load_module]
common_fields = true
data_type = 603

[structures.load_module.additional_fields]
ko_file = { index = 0, type = "kernel" }
pid_tree = { index = 1, type = "kernel" }
run_path = { index = 2, type = "kernel" }

# [structures.mprotect]
# common_fields = true
# data_type = 10

# [structures.mprotect.additional_fields]
# mprotect_prot = { index = 0, type = "kernel" }
# owner_pid = { index = 1, type = "kernel" }
# owner_file = { index = 2, type = "kernel" }
# vm_pid = { index = 3, type = "kernel" }
# pid_tree = { index = 4, type = "kernel" }

[structures.create_file]
common_fields = true
data_type = 602

[structures.create_file.additional_fields]
file_path = { index = 0, type = "kernel" }
dip = { index = 1, type = "kernel" }
dport = { index = 2, type = "kernel" }
sip = { index = 3, type = "kernel" }
sport = { index = 4, type = "kernel" }
sa_family = { index = 5, type = "kernel" }
socket_pid = { index = 6, type = "kernel" }
socket_argv = { index = 7, type = "user" }


[structures.dns]
common_fields = true
data_type = 601

[structures.dns.additional_fields]
query = { index = 0, type = "kernel" }
sa_family = { index = 1, type = "kernel" }
dip = { index = 2, type = "kernel" }
dport = { index = 3, type = "kernel" }
sip = { index = 4, type = "kernel" }
sport = { index = 5, type = "kernel" }
qr = { index = 6, type = "kernel" }
opcode = { index = 7, type = "kernel" }
rcode = { index = 8, type = "kernel" }

[structures.proc_file_hook]
common_fields = false
data_type = 700

[structures.proc_file_hook.additional_fields]
data_type = { index = 1, type = "kernel" }
module_name = { index = 2, type = "kernel" }
hidden = { index = 3, type = "kernel" }
timestamp = { index = 4, type = "user" }

[structures.syscall_hook]
common_fields = false
data_type = 701

[structures.syscall_hook.additional_fields]
data_type = { index = 1, type = "kernel" }
module_name = { index = 2, type = "kernel" }
hidden = { index = 3, type = "kernel" }
syscall_number = { index = 4, type = "kernel" }
timestamp = { index = 5, type = "user" }

[structures.lkm_hidden]
common_fields = false
data_type = 702

[structures.lkm_hidden.additional_fields]
data_type = { index = 1, type = "kernel" }
module_name = { index = 2, type = "kernel" }
hidden = { index = 3, type = "kernel" }
timestamp = { index = 4, type = "user" }

[structures.interrupts_hook]
common_fields = false
data_type = 703

[structures.interrupts_hook.additional_fields]
data_type = { index = 1, type = "kernel" }
module_name = { index = 2, type = "kernel" }
hidden = { index = 3, type = "kernel" }
interrupts_number = { index = 4, type = "kernel" }
timestamp = { index = 5, type = "user" }

# [structures.open]
# common_fields = true
# data_type = 2

# [structures.open.additional_fields]
# flags = { index = 0, type = "kernel" }
# mode = { index = 1, type = "kernel" }
# file = { index = 2, type = "kernel" }

# [structures.nano_sleep]
# common_fields = true
# data_type = 35

# [structures.nano_sleep.additional_fields]
# sec = { index = 0, type = "kernel" }
# nsec = { index = 1, type = "kernel" }

# [structures.accept]
# common_fields = true
# data_type = 43

# [structures.accept.additional_fields]
# sa_family = { index = 0, type = "kernel" }
# dip = { index = 1, type = "kernel" }
# dport = { index = 2, type = "kernel" }
# sip = { index = 3, type = "kernel" }
# sport = { index = 4, type = "kernel" }
# res = { index = 5, type = "kernel" }

# [structures.exit]
# common_fields = true
# data_type = 60

# [structures.kill]
# common_fields = true
# data_type = 62

# [structures.kill.additional_fields]
# target_pid = { index = 0, type = "kernel" }
# sig = { index = 1, type = "kernel" }

[structures.rename]
common_fields = true
data_type = 82

[structures.rename.additional_fields]
run_path = { index = 0, type = "kernel" }
old_name = { index = 1, type = "kernel" }
new_name = { index = 2, type = "kernel" }

[structures.link]
common_fields = true
data_type = 86

[structures.link.additional_fields]
run_path = { index = 0, type = "kernel" }
old_name = { index = 1, type = "kernel" }
new_name = { index = 2, type = "kernel" }

[structures.setsid]
common_fields = true
data_type = 112

[structures.prctl]
common_fields = true
data_type = 157

[structures.prctl.additional_fields]
option = { index = 0, type = "kernel" }
new_name = { index = 1, type = "kernel" }

# [structures.tkill]
# common_fields = true
# data_type = 200

# [structures.tkill.additional_fields]
# target_pid = { index = 0, type = "kernel" }
# sig = { index = 1, type = "kernel" }

# [structures.exit_group]
# common_fields = true
# data_type = 231

[structures.memfd_create]
common_fields = true
data_type = 356

[structures.memfd_create.additional_fields]
fdname = { index = 0, type = "kernel" }
flags = { index = 1, type = "kernel" }

# [structures.unlink]
# common_fields = true
# data_type = 605
# [structures.unlink.additional_fields]
# file = { index = 0, type = "kernel" }

# [structures.rmdir]
# common_fields = true
# data_type = 606
# [structures.rmdir.additional_fields]
# file = { index = 0, type = "kernel" }
