[book]
tittle = "Elkeid Docs"
authors = ["Elkeid team"]
src = "."
description = ""

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[preprocessor.filter]
command = "python3 filter.py"

[output.html]
git-repository-url = "https://elkeid.bytedance.com/Chinese/"
git-repository-icon = "fa-language"

