name: Elkeid_rasp

on:
  push:
    tags: [ rasp-v* ]

jobs:

  build:
    runs-on: RASP
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: |
        curl -fsSL https://lf3-static.bytednsdoc.com/obj/eden-cn/kplrsl/ljhwZthlaukjlkulzlp/php-headers.tar.gz | tar -xz -C rasp/php
        docker run --rm --pull=always -v $(pwd):/Elkeid hackerl/rasp-toolchain \
        make -C /Elkeid/rasp \
          STATIC=TRUE \
          PY_PREBUILT=TRUE \
          CC=/opt/x86_64-linux-musl-native/bin/x86_64-linux-musl-gcc \
          CXX=/opt/x86_64-linux-musl-native/bin/x86_64-linux-musl-g++ \
          LD=/opt/x86_64-linux-musl-native/bin/ld \
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=/opt/x86_64-linux-musl-native/bin/ld \
          GNU_CC=/opt/gcc-10.4.0/bin/gcc \
          GNU_CXX=/opt/gcc-10.4.0/bin/g++ \
          PHP_HEADERS=/Elkeid/rasp/php/php-headers \
          PYTHON2_INCLUDE=/usr/include/python2.7 \
          PYTHON3_INCLUDE=/usr/include/python3.6m \
          VERSION=${GITHUB_REF#refs/*/rasp-v} \
          -j$(nproc) 

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rasp/rasp-*.tar.gz
          rasp/SHA256SUMS
